version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - aws-cli/setup
      - node/install:
          node-version: "16.13"

      - run:
          name: Front-End Install
          command: |
            npm run frontend:install

      - run:
          name: Front-End Build
          command: |
            npm run frontend:build

      - run:
          name: Back-End Install
          command: |
            npm run backend:install

      - run:
          name: Back-End Build
          command: |
            npm run backend:build

      - persist_to_workspace:
          root: workspace
          paths:
            - udagram_frontend/www
            - udagram_api/www

  deploy:
    docker:
      - image: "cimg/base:stable"

    working_directory: $CIRCLE_WORKING_DIRECTORY

    steps:
      - attach_workspace:
          at: $CIRCLE_WORKING_DIRECTORY
      - aws-cli/setup
      - node/install:
          node-version: "16.13"

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --delete
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: "udagram_frontend/www"
          to: "s3://my-udagram-frontend"

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
