version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-s3: circleci/aws-s3@3.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    filters:
      branches:
        only: master

    working_directory: ~/udacity_deployment_project
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout:
          path: ~/udacity_deployment_project
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup
      - eb/setup
      - node/install:
          node-version: "16.13"

      - run:
          name: Front-End Install
          command: |
            npm run frontend:install

      - run:
          name: Front-End Test
          command: |
            npm run frontend:test

      - run:
          name: Front-End Build
          command: |
            npm run frontend:build

      - run:
          name: Back-End Install
          command: |
            npm run backend:install

      - run:
          name: Back-End Build
          command: |
            npm run backend:build

      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy

      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
